namespace FireplaceApi.Core.Enums
{
    public enum ErrorName
    {
        /// <summary>
        /// Internal server error
        /// </summary>
        INTERNAL_SERVER,

        /// <summary>
        /// Main business logic errors
        /// </summary>
        BAD_REQUEST,
        AUTHENTICATION_FAILED,
        OLD_PASSWORD_NOT_CORRECT,
        EMAIL_ACTIVATION_CODE_NOT_CORRECT,
        RESET_PASSWORD_CODE_NOT_CORRECT,
        MAX_REQUEST_LIMIT,

        /// <summary>
        /// Access Denied and Existance errors
        /// </summary>
        ACCESS_DENIED,
        USER_DOES_NOT_EXIST_OR_ACCESS_DENIED,
        USERNAME_ALREADY_EXISTS,
        EMAIL_ADDRESS_EXISTS,
        EMAIL_ADDRESS_DOES_NOT_EXIST_OR_ACCESS_DENIED,
        ERROR_CODE_DOES_NOT_EXIST_OR_ACCESS_DENIED,
        ACCESS_TOKEN_VALUE_DOES_NOT_EXIST_OR_ACCESS_DENIED,
        SESSION_ID_DOES_NOT_EXIST_OR_ACCESS_DENIED,
        COMMUNITY_DOES_NOT_EXIST,
        COMMUNITY_ALREADY_EXISTS,
        COMMUNITY_MEMBERSHIP_NOT_EXIST,
        COMMUNITY_MEMBERSHIP_ALREADY_EXISTS,
        POST_DOES_NOT_EXIST,
        COMMENT_DOES_NOT_EXIST,
        USER_CAN_NOT_ALTER_COMMUNITY,
        USER_CAN_NOT_ALTER_COMMUNITY_MEMBERSHIP,
        USER_CAN_NOT_ALTER_POST,
        USER_CAN_NOT_ALTER_COMMENT,
        COMMENT_VOTE_ALREADY_EXISTS,
        COMMENT_VOTE_DOES_NOT_EXIST,
        POST_VOTE_ALREADY_EXISTS,
        POST_VOTE_DOES_NOT_EXIST,
        EMAIL_IS_ALREADY_ACTIVATED,

        /// <summary>
        /// Format errors
        /// </summary>
        REQUEST_CONTENT_TYPE_IS_NOT_VALID,
        REQUEST_BODY_IS_NOT_JSON,
        PASSWORD_MIN_LENGTH,
        PASSWORD_MAX_LENGTH,
        PASSWORD_AN_UPPERCASE_LETTER,
        PASSWORD_A_NUMBER,
        PASSWORD_A_LOWERCASE_LETTER,
        PASSWORD_VALID_CHARACTERS,
        USERNAME_MIN_LENGTH,
        USERNAME_MAX_LENGTH,
        USERNAME_WRONG_START,
        USERNAME_WRONG_END,
        USERNAME_INVALID_CONSECUTIVE,
        USERNAME_VALID_CHARACTERS,
        EMAIL_ADDRESS_NOT_VALID,
        ERROR_CLIENT_MESSAGE_NOT_VALID,
        ACCESS_TOKEN_VALUE_IS_NOT_VALID,
        INPUT_SORT_IS_NOT_VALID,
        COMMENT_CONTENT_MAX_LENGTH,
        POST_CONTENT_MAX_LENGTH,
        ENCODED_ID_FORMAT_IS_NOT_VALID,
        DISPLAY_NAME_FORMAT_IS_NOT_VALID,
        ABOUT_FORMAT_IS_NOT_VALID,
        URL_FORMAT_IS_NOT_VALID,

        /// <summary>
        /// Missing parameter(s) errors
        /// </summary>
        USERNAME_IS_MISSING,
        PASSWORD_IS_MISSING,
        EMAIL_ADDRESS_IS_MISSING,
        USER_ID_IS_MISSING,
        REQUIRED_BOTH_OF_OLD_PASSWORD_AND_PASSWORD,
        EMAIL_ID_IS_MISSING,
        ACTIVATION_CODE_IS_MISSING,
        ERROR_CODE_IS_MISSING,
        ACCESS_TOKEN_VALUE_IS_MISSING,
        SESSION_ID_IS_MISSING,
        PAGINATION_POINTER_IS_MISSING,
        IS_UPVOTE_IS_MISSING,
        RESET_PASSWORD_CODE_IS_MISSING
    }
}
