namespace FireplaceApi.Core.Enums
{
    public enum ErrorName
    {
        // Internal server error
        INTERNAL_SERVER,

        // Main business logic errors
        BAD_REQUEST,
        AUTHENTICATION_FAILED,
        OLD_PASSWORD_NOT_CORRECT,
        EMAIL_ACTIVATION_CODE_NOT_CORRECT,


        // Access Denied and Existance errors
        ACCESS_DENIED,

        USER_DOES_NOT_EXIST_OR_ACCESS_DENIED,

        USERNAME_ALREADY_EXISTS,
        USERNAME_DOES_NOT_EXIST_OR_ACCESS_DENIED,

        EMAIL_ADDRESS_EXISTS,
        EMAIL_ADDRESS_DOES_NOT_EXIST_OR_ACCESS_DENIED,

        EMAIL_ID_EXISTS,
        EMAIL_ID_DOES_NOT_EXIST_OR_ACCESS_DENIED,

        ERROR_CODE_DOES_NOT_EXIST_OR_ACCESS_DENIED,

        ACCESS_TOKEN_VALUE_DOES_NOT_EXIST_OR_ACCESS_DENIED,

        SESSION_ID_DOES_NOT_EXIST_OR_ACCESS_DENIED,

        PAGINATION_POINTER_DOES_NOT_EXIST,

        COMMUNITY_DOES_NOT_EXIST,
        COMMUNITY_ALREADY_EXISTS,
        COMMUNITY_MEMBERSHIP_NOT_EXIST,
        COMMUNITY_MEMBERSHIP_ALREADY_EXISTS,
        POST_DOES_NOT_EXIST,
        COMMENT_DOES_NOT_EXIST,
        USER_CAN_NOT_ALTER_COMMUNITY,
        USER_CAN_NOT_ALTER_COMMUNITY_MEMBERSHIP,
        USER_CAN_NOT_ALTER_POST,
        USER_CAN_NOT_ALTER_COMMENT,

        //// New


        // Format errors
        REQUEST_CONTENT_TYPE_IS_NOT_VALID,
        REQUEST_BODY_IS_NOT_JSON,
        PASSWORD_MIN_LENGTH,
        PASSWORD_MAX_LENGTH,
        PASSWORD_AN_UPPERCASE_LETTER,
        PASSWORD_A_NUMBER,
        PASSWORD_A_LOWERCASE_LETTER,
        PASSWORD_VALID_CHARACTERS,

        USERNAME_MIN_LENGTH,
        USERNAME_MAX_LENGTH,
        USERNAME_WRONG_START,
        USERNAME_WRONG_END,
        USERNAME_INVALID_CONSECUTIVE,
        USERNAME_VALID_CHARACTERS,

        EMAIL_ADDRESS_NOT_VALID,

        FIRST_NAME_NOT_VALID,
        LAST_NAME_NOT_VALID,

        ERROR_CLIENT_MESSAGE_NOT_VALID,

        ACCESS_TOKEN_VALUE_IS_NOT_VALID,

        PAGINATION_LIMIT_MIN_LIMIT,
        PAGINATION_LIMIT_MAX_LIMIT,
        PAGINATION_PAGE_POINTER_NOT_VALID,
        PAGINATION_OFFSET_OUT_OF_RANGE,
        PAGINATION_PAGE_OUT_OF_RANGE,

        INPUT_SORT_IS_NOT_VALID,

        COMMENT_CONTENT_MAX_LENGTH,
        POST_CONTENT_MAX_LENGTH,

        //// New

        // Missing parameter(s) errors
        FIRST_NAME_IS_MISSING,
        LAST_NAME_IS_MISSING,
        USERNAME_IS_MISSING,
        PASSWORD_IS_MISSING,
        EMAIL_ADDRESS_IS_MISSING,
        USER_ID_IS_MISSING,
        REQUIRED_BOTH_OF_OLD_PASSWORD_AND_PASSWORD,
        EMAIL_ID_IS_MISSING,
        ACTIVATION_CODE_IS_MISSING,
        ERROR_CODE_IS_MISSING,
        ACCESS_TOKEN_VALUE_IS_MISSING,
        SESSION_ID_IS_MISSING,
        PAGINATION_POINTER_IS_MISSING,
        COMMUNITY_ID_AND_NAME_ARE_MISSING,

        //// New
    }
}
