	-- Configs

INSERT INTO public."ConfigsEntities" VALUES (0, 'DEVELOPMENT', '{"Api":{"BaseUrlPath":"http://localhost:5000","CookieMaxAgeInDays":30},"File":{"BasePhysicalPath":"path/to/files","BaseUrlPath":"https://files.server.com","GeneratedFileNameLength":12},"Email":{"ActivationSubject":"Project Email Activation","ActivationMessageFormat":"Congratulations! Code: {0}"},"Google":{"ClientId":"<client-id>","ClientSecret":"<client-secret>","RelativeRedirectUrl":"/users/log-in-with-google"},"Pagination":{"TotalItemsCount":300,"GeneratedPointerLength":10,"MaximumOfPageItemsCount":30}}', CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ConfigsEntities" VALUES (1, 'PRODUCTION', '{"Api":{"BaseUrlPath":"http://api.server.com","CookieMaxAgeInDays":30},"File":{"BasePhysicalPath":"path/to/files","BaseUrlPath":"https://files.server.com","GeneratedFileNameLength":12},"Email":{"ActivationSubject":"Project Email Activation","ActivationMessageFormat":"Congratulations! Code: {0}"},"Google":{"ClientId":"<client-id>","ClientSecret":"<client-secret>","RelativeRedirectUrl":"/users/log-in-with-google"},"Pagination":{"TotalItemsCount":300,"GeneratedPointerLength":10,"MaximumOfPageItemsCount":30}}', CURRENT_TIMESTAMP(0), NULL);


-- Errors

INSERT INTO public."ErrorEntities" VALUES (0, 'INTERNAL_SERVER', 5000, 'Something Went Wrong!', 500, CURRENT_TIMESTAMP(0), NULL);

INSERT INTO public."ErrorEntities" VALUES (1, 'BAD_REQUEST', 6001, 'Wrong Request!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (2, 'AUTHENTICATION_FAILED', 6002, 'AUTHENTICATION_FAILED!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (3, 'OLD_PASSWORD_NOT_CORRECT', 6003, 'OLD_PASSWORD_NOT_CORRECT!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (4, 'EMAIL_ACTIVATION_CODE_NOT_CORRECT', 6004, 'EMAIL_ACTIVATION_CODE_NOT_CORRECT!', 400, CURRENT_TIMESTAMP(0), NULL);

INSERT INTO public."ErrorEntities" VALUES (5, 'ACCESS_DENIED', 6200, 'Access Denied!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (6, 'USER_DOES_NOT_EXIST_OR_ACCESS_DENIED', 6202, 'USER_DOES_NOT_EXIST_OR_ACCESS_DENIED!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (7, 'USERNAME_ALREADY_EXISTS', 6203, 'USERNAME_ALREADY_EXISTS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (8, 'EMAIL_ADDRESS_EXISTS', 6205, 'EMAIL_ADDRESS_EXISTS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (9, 'EMAIL_ADDRESS_DOES_NOT_EXIST_OR_ACCESS_DENIED', 6206, 'EMAIL_ADDRESS_DOES_NOT_EXIST_OR_ACCESS_DENIED!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (10, 'ERROR_CODE_DOES_NOT_EXIST_OR_ACCESS_DENIED', 6209, 'ERROR_CODE_DOES_NOT_EXIST_OR_ACCESS_DENIED!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (11, 'ACCESS_TOKEN_VALUE_DOES_NOT_EXIST_OR_ACCESS_DENIED', 6210, 'ACCESS_TOKEN_VALUE_DOES_NOT_EXIST_OR_ACCESS_DENIED!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (12, 'SESSION_ID_DOES_NOT_EXIST_OR_ACCESS_DENIED', 6211, 'SESSION_ID_DOES_NOT_EXIST_OR_ACCESS_DENIED!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (13, 'PAGINATION_POINTER_DOES_NOT_EXIST', 6212, 'PAGINATION_POINTER_DOES_NOT_EXIST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (14, 'COMMUNITY_DOES_NOT_EXIST', 6213, 'COMMUNITY_DOES_NOT_EXIST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (15, 'COMMUNITY_ALREADY_EXISTS', 6214, 'COMMUNITY_ALREADY_EXISTS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (16, 'COMMUNITY_MEMBERSHIP_NOT_EXIST', 6215, 'COMMUNITY_MEMBERSHIP_NOT_EXIST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (17, 'COMMUNITY_MEMBERSHIP_ALREADY_EXISTS', 6216, 'COMMUNITY_MEMBERSHIP_ALREADY_EXISTS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (18, 'POST_DOES_NOT_EXIST', 6217, 'POST_DOES_NOT_EXIST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (19, 'COMMENT_DOES_NOT_EXIST', 6218, 'COMMENT_DOES_NOT_EXIST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (20, 'USER_CAN_NOT_ALTER_COMMUNITY', 6219, 'USER_CAN_NOT_ALTER_COMMUNITY!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (21, 'USER_CAN_NOT_ALTER_COMMUNITY_MEMBERSHIP', 6220, 'USER_CAN_NOT_ALTER_COMMUNITY_MEMBERSHIP!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (22, 'USER_CAN_NOT_ALTER_POST', 6221, 'USER_CAN_NOT_ALTER_POST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (23, 'USER_CAN_NOT_ALTER_COMMENT', 6222, 'USER_CAN_NOT_ALTER_COMMENT!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (24, 'COMMENT_VOTE_ALREADY_EXISTS', 6223, 'COMMENT_VOTE_ALREADY_EXISTS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (25, 'COMMENT_VOTE_DOES_NOT_EXIST', 6224, 'COMMENT_VOTE_DOES_NOT_EXIST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (26, 'POST_VOTE_ALREADY_EXISTS', 6225, 'POST_VOTE_ALREADY_EXISTS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (27, 'POST_VOTE_DOES_NOT_EXIST', 6226, 'POST_VOTE_DOES_NOT_EXIST!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (28, 'EMAIL_IS_ALREADY_ACTIVATED', 6227, 'EMAIL_IS_ALREADY_ACTIVATED!', 400, CURRENT_TIMESTAMP(0), NULL);

INSERT INTO public."ErrorEntities" VALUES (29, 'REQUEST_CONTENT_TYPE_IS_NOT_VALID', 6400, 'REQUEST_CONTENT_TYPE_IS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (30, 'REQUEST_BODY_IS_NOT_JSON', 6401, 'REQUEST_BODY_IS_NOT_JSON!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (31, 'PASSWORD_MIN_LENGTH', 6402, 'PASSWORD_MIN_LENGTH!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (32, 'PASSWORD_MAX_LENGTH', 6403, 'PASSWORD_MAX_LENGTH!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (33, 'PASSWORD_AN_UPPERCASE_LETTER', 6404, 'PASSWORD_AN_UPPERCASE_LETTER!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (34, 'PASSWORD_A_NUMBER', 6405, 'PASSWORD_A_NUMBER!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (35, 'PASSWORD_A_LOWERCASE_LETTER', 6406, 'PASSWORD_A_LOWERCASE_LETTER!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (36, 'PASSWORD_VALID_CHARACTERS', 6407, 'PASSWORD_VALID_CHARACTERS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (37, 'USERNAME_MIN_LENGTH', 6408, 'USERNAME_MIN_LENGTH!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (38, 'USERNAME_MAX_LENGTH', 6409, 'USERNAME_MAX_LENGTH!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (39, 'USERNAME_WRONG_START', 6410, 'USERNAME_WRONG_START!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (40, 'USERNAME_WRONG_END', 6411, 'USERNAME_WRONG_END!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (41, 'USERNAME_INVALID_CONSECUTIVE', 6412, 'USERNAME_INVALID_CONSECUTIVE!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (42, 'USERNAME_VALID_CHARACTERS', 6413, 'USERNAME_VALID_CHARACTERS!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (43, 'EMAIL_ADDRESS_NOT_VALID', 6414, 'EMAIL_ADDRESS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (44, 'ERROR_CLIENT_MESSAGE_NOT_VALID', 6417, 'ERROR_CLIENT_MESSAGE_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (45, 'ACCESS_TOKEN_VALUE_IS_NOT_VALID', 6418, 'ACCESS_TOKEN_VALUE_IS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (46, 'PAGINATION_LIMIT_MIN_LIMIT', 6419, 'PAGINATION_LIMIT_MIN_LIMIT!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (47, 'PAGINATION_LIMIT_MAX_LIMIT', 6420, 'PAGINATION_LIMIT_MAX_LIMIT!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (48, 'PAGINATION_PAGE_POINTER_NOT_VALID', 6421, 'PAGINATION_PAGE_POINTER_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (49, 'PAGINATION_OFFSET_OUT_OF_RANGE', 6422, 'PAGINATION_OFFSET_OUT_OF_RANGE!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (50, 'PAGINATION_PAGE_OUT_OF_RANGE', 6423, 'PAGINATION_PAGE_OUT_OF_RANGE!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (51, 'INPUT_SORT_IS_NOT_VALID', 6424, 'INPUT_SORT_IS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (52, 'COMMENT_CONTENT_MAX_LENGTH', 6425, 'COMMENT_CONTENT_MAX_LENGTH!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (53, 'POST_CONTENT_MAX_LENGTH', 6426, 'POST_CONTENT_MAX_LENGTH!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (54, 'ENCODED_ID_FORMAT_IS_NOT_VALID', 6427, 'ENCODED_ID_FORMAT_IS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (55, 'DISPLAY_NAME_FORMAT_IS_NOT_VALID', 6428, 'DISPLAY_NAME_FORMAT_IS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (56, 'ABOUT_FORMAT_IS_NOT_VALID', 6429, 'ABOUT_FORMAT_IS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (57, 'URL_FORMAT_IS_NOT_VALID', 6430, 'URL_FORMAT_IS_NOT_VALID!', 400, CURRENT_TIMESTAMP(0), NULL);

INSERT INTO public."ErrorEntities" VALUES (58, 'USERNAME_IS_MISSING', 6603, 'USERNAME_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (59, 'PASSWORD_IS_MISSING', 6604, 'PASSWORD_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (60, 'EMAIL_ADDRESS_IS_MISSING', 6605, 'EMAIL_ADDRESS_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (61, 'USER_ID_IS_MISSING', 6606, 'USER_ID_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (62, 'REQUIRED_BOTH_OF_OLD_PASSWORD_AND_PASSWORD', 6607, 'REQUIRED_BOTH_OF_OLD_PASSWORD_AND_PASSWORD!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (63, 'EMAIL_ID_IS_MISSING', 6608, 'EMAIL_ID_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (64, 'ACTIVATION_CODE_IS_MISSING', 6609, 'ACTIVATION_CODE_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (65, 'ERROR_CODE_IS_MISSING', 6610, 'ERROR_CODE_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (66, 'ACCESS_TOKEN_VALUE_IS_MISSING', 6611, 'ACCESS_TOKEN_VALUE_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (67, 'SESSION_ID_IS_MISSING', 6612, 'SESSION_ID_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (68, 'PAGINATION_POINTER_IS_MISSING', 6613, 'PAGINATION_POINTER_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
INSERT INTO public."ErrorEntities" VALUES (69, 'IS_UPVOTE_IS_MISSING', 6614, 'IS_UPVOTE_IS_MISSING!', 400, CURRENT_TIMESTAMP(0), NULL);
